from setuptools import setup, find_packages

setup(
    name="preflight-integration-tester",
    version="0.1.0",
    description="Pre-purchase AI readiness diagnostic for enterprise systems",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Preflight Team",
    author_email="support@preflight.ai",
    url="https://github.com/marcuspat/preflight-integration-tester",
    license="MIT",
    packages=find_packages(exclude=["tests*"]),
    python_requires=">=3.9",
    install_requires=[
        "pydantic>=2.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "click>=8.1.0",
        "rich>=13.0.0",
        "pyyaml>=6.0",
        "jinja2>=3.1.0",
        "sqlalchemy>=2.0.0",
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "structlog>=23.0.0",
        "python-dotenv>=1.0.0",
        "httpx>=0.24.0",
        "aiohttp>=3.8.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "ruff>=0.1.0",
            "mypy>=1.5.0",
        ],
        "connectors": [
            "simple-salesforce>=1.12.0",
            "psycopg2-binary>=2.9.0",
            "snowflake-connector-python>=3.0.0",
            "pymysql>=1.1.0",
        ],
        "enterprise": [
            "redis>=4.6.0",
            "celery>=5.3.0",
            "prometheus-client>=0.17.0",
            "sentry-sdk>=1.28.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "preflight=preflight.cli.main:cli",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Testing",
        "Topic :: System :: Systems Administration",
    ],
)
