"""
Domain aggregates for the Preflight domain model.

Aggregates are clusters of entities and value objects treated as a single unit
for the purpose of data changes.  Each aggregate has a root entity that enforces
invariants and is the only entry point for external modifications.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from .value_objects import (
    EffortEstimate,
    EffortLevel,
    ReadinessScore,
    ReadinessVerdict,
    SeverityLevel,
)
from .entities import (
    ConnectionProfile,
    EntityMapping,
    MiddlewareGap,
    PipelineBottleneck,
    RemediationItem,
    SchemaInconsistency,
)
from .events import (
    DiagnosticRunCompleted,
    DiagnosticRunStarted,
    DomainEvent,
)


@dataclass
class AnalysisResults:
    """Aggregate holding all analysis results for a diagnostic run.

    This aggregate is populated progressively by the analysis phase of the
    diagnostic pipeline.

    Attributes:
        id: Unique identifier for this result set.
        entity_mappings: Cross-system entity mappings produced by schema analysis.
        schema_inconsistencies: All schema inconsistencies detected.
        pipeline_bottlenecks: All pipeline bottlenecks detected.
        middleware_gaps: All middleware gaps detected.
        data_quality_issues: Free-form data quality findings (raw dicts for
            flexibility until the data-quality entity is formalised).
        completed_at: UTC timestamp of when all analysis phases finished.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    entity_mappings: List[EntityMapping] = field(default_factory=list)
    schema_inconsistencies: List[SchemaInconsistency] = field(default_factory=list)
    pipeline_bottlenecks: List[PipelineBottleneck] = field(default_factory=list)
    middleware_gaps: List[MiddlewareGap] = field(default_factory=list)
    data_quality_issues: List[Dict[str, Any]] = field(default_factory=list)
    completed_at: Optional[datetime] = None

    @property
    def critical_count(self) -> int:
        """Return the total number of CRITICAL-severity issues across all finding types."""
        all_issues: List[Any] = (
            list(self.schema_inconsistencies)
            + list(self.pipeline_bottlenecks)
            + list(self.middleware_gaps)
        )
        return sum(1 for i in all_issues if i.severity == SeverityLevel.CRITICAL)

    @property
    def blocking_gaps(self) -> List[MiddlewareGap]:
        """Return only the middleware gaps that block deployment."""
        return [g for g in self.middleware_gaps if g.blocking]


@dataclass
class SimulationScenario:
    """Describes the AI deployment scenario being simulated.

    The scenario drives both the pipeline load-simulation parameters and
    the context used to generate the executive summary.

    Attributes:
        name: Short name for the scenario (e.g. ``CRM AI Assistant``).
        description: Longer description of what the AI workload does.
        target_systems: List of system identifiers included in the simulation.
        concurrent_users: Number of simultaneous users in the load model.
        queries_per_minute: Baseline query rate for the load model.
        peak_multiplier: Burst factor applied to the baseline QPM.
        response_time_target_ms: SLO target for response time in milliseconds.
        business_entities: Names of the business entities the AI workload touches.
        use_case: Free-text description of the AI use case.
    """

    name: str = ""
    description: str = ""
    target_systems: List[str] = field(default_factory=list)
    concurrent_users: int = 10
    queries_per_minute: int = 100
    peak_multiplier: float = 2.0
    response_time_target_ms: int = 500
    business_entities: List[str] = field(default_factory=list)
    use_case: str = ""


@dataclass
class ReadinessReport:
    """The final readiness report aggregate.

    This is the primary deliverable of a diagnostic run.  It is generated by
    the :class:`~preflight.core.application.services.report_service.ReportService`
    and attached to the :class:`DiagnosticRun` on completion.

    Attributes:
        id: Unique identifier for this report.
        readiness_score: Computed readiness score (0–100).
        verdict: Readiness verdict derived from the score.
        executive_summary: Non-technical summary for C-suite stakeholders.
        technical_summary: Detailed summary for engineering teams.
        remediation_plan: Ordered list of remediation actions.
        total_effort_estimate: Aggregate effort for the entire remediation plan.
        generated_at: UTC timestamp of report generation.
        findings_summary: Dict mapping finding category to finding count,
            e.g. ``{"schema": 3, "pipeline": 1}``.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    readiness_score: Optional[ReadinessScore] = None
    verdict: Optional[ReadinessVerdict] = None
    executive_summary: str = ""
    technical_summary: str = ""
    remediation_plan: List[RemediationItem] = field(default_factory=list)
    total_effort_estimate: Optional[EffortEstimate] = None
    generated_at: Optional[datetime] = None
    findings_summary: Dict[str, int] = field(default_factory=dict)

    def calculate_score(
        self,
        analysis: "AnalysisResults",
        weights: Optional[Dict[str, float]] = None,
    ) -> ReadinessScore:
        """Calculate and store a readiness score from analysis results.

        Each finding category incurs a severity-weighted penalty subtracted from
        a perfect score of 100.  The final score is clamped to [0, 100].

        Args:
            analysis: The :class:`AnalysisResults` to score.
            weights: Optional override for category weights.  Keys must match
                the default weight dict.

        Returns:
            The computed :class:`ReadinessScore`, which is also stored on
            ``self.readiness_score``.
        """
        default_weights: Dict[str, float] = {
            "schema_inconsistency": 0.30,
            "pipeline_bottleneck": 0.25,
            "middleware_gap": 0.20,
            "data_quality": 0.15,
            "security_concern": 0.10,
        }
        w = weights or default_weights

        # Severity multipliers (penalty points per finding)
        severity_penalty: Dict[SeverityLevel, int] = {
            SeverityLevel.CRITICAL: 20,
            SeverityLevel.HIGH: 10,
            SeverityLevel.MEDIUM: 5,
            SeverityLevel.LOW: 2,
            SeverityLevel.INFO: 0,
        }

        schema_penalty = sum(
            severity_penalty.get(i.severity, 5) for i in analysis.schema_inconsistencies
        )
        pipeline_penalty = sum(
            severity_penalty.get(b.severity, 5) for b in analysis.pipeline_bottlenecks
        )
        middleware_penalty = sum(
            severity_penalty.get(g.severity, 5) for g in analysis.middleware_gaps
        )
        dq_penalty = len(analysis.data_quality_issues) * 3

        total_penalty = (
            schema_penalty * w["schema_inconsistency"]
            + pipeline_penalty * w["pipeline_bottleneck"]
            + middleware_penalty * w["middleware_gap"]
            + dq_penalty * w["data_quality"]
        )

        score = max(0.0, min(100.0, 100.0 - total_penalty))
        self.readiness_score = ReadinessScore(value=score)
        self.verdict = self.readiness_score.verdict
        return self.readiness_score


@dataclass
class DiagnosticRun:
    """Root aggregate for a full Preflight diagnostic run.

    ``DiagnosticRun`` is the central aggregate of the domain.  It tracks the
    lifecycle of the diagnostic process and owns all sub-aggregates
    (connections, analysis, report).  External code must mutate this aggregate
    only through its public methods to preserve invariants.

    Attributes:
        id: Unique identifier for this run.
        name: Human-readable name for the run.
        status: Current lifecycle state:
            ``pending`` → ``running`` → ``analyzing`` → ``reporting``
            → ``completed`` | ``failed``.
        scenario: The simulation scenario configuration.
        connections: All connection profiles for this run.
        analysis: Analysis results, populated after the analysis phase.
        report: Readiness report, populated after the reporting phase.
        created_at: UTC timestamp of run creation.
        started_at: UTC timestamp of when the run transitioned to *running*.
        completed_at: UTC timestamp of when the run finished (any terminal state).
        error_message: Error detail, populated when ``status == "failed"``.
        progress_pct: Rough completion percentage (0.0–100.0).
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    status: str = "pending"  # pending, running, analyzing, reporting, completed, failed
    scenario: Optional[SimulationScenario] = None
    connections: List[ConnectionProfile] = field(default_factory=list)
    analysis: Optional[AnalysisResults] = None
    report: Optional[ReadinessReport] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None
    progress_pct: float = 0.0
    _events: List[DomainEvent] = field(default_factory=list, repr=False)

    def start(self) -> None:
        """Transition the run to the *running* state and record a start event."""
        self.status = "running"
        self.started_at = datetime.utcnow()
        self._events.append(DiagnosticRunStarted(run_id=self.id))

    def add_connection(self, profile: ConnectionProfile) -> None:
        """Attach a connection profile to this run.

        Args:
            profile: The :class:`ConnectionProfile` to add.
        """
        self.connections.append(profile)

    def complete_analysis(self, results: AnalysisResults) -> None:
        """Store analysis results and advance the run to the *reporting* state.

        Args:
            results: The completed :class:`AnalysisResults` aggregate.
        """
        self.analysis = results
        self.status = "reporting"
        self.progress_pct = 80.0

    def complete(self, report: ReadinessReport) -> None:
        """Finalise the run with the generated report and transition to *completed*.

        Args:
            report: The finished :class:`ReadinessReport` to attach.
        """
        self.report = report
        self.status = "completed"
        self.completed_at = datetime.utcnow()
        self.progress_pct = 100.0
        self._events.append(
            DiagnosticRunCompleted(
                run_id=self.id,
                verdict=report.verdict.value if report.verdict else "UNKNOWN",
                score=report.readiness_score.value if report.readiness_score else 0.0,
            )
        )

    def fail(self, error: str) -> None:
        """Transition the run to the *failed* state.

        Args:
            error: Human-readable description of the failure.
        """
        self.status = "failed"
        self.error_message = error
        self.completed_at = datetime.utcnow()

    def pop_events(self) -> List[DomainEvent]:
        """Drain and return all pending domain events.

        Callers are responsible for dispatching the returned events to any
        subscribers.  After this call the internal event list is empty.

        Returns:
            A list of :class:`DomainEvent` instances in the order they were raised.
        """
        events = list(self._events)
        self._events.clear()
        return events

    @property
    def active_connections(self) -> List[ConnectionProfile]:
        """Return only the connections whose status is *connected*."""
        return [c for c in self.connections if c.status == "connected"]
